# Set update schedule for GitHub Actions

version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          # Check for updates to GitHub Actions every weekday
          interval: 'daily'
          time: '05:00'
          timezone: 'Europe/Berlin'
    # Maintain dependencies for npm
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '06:00'
          timezone: 'Europe/Berlin'
      allow:
          - dependency-name: '@plentymarkets*'
