# This is displayed in the pr check area
name: Test Strictify

# Controls when the action will run. Triggers the workflow on pull request events
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test-strictify:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ./node_modules
                  key: ${{ hashFiles('**/package-lock.json') }}

            # Clean install of the node dependencies
            - name: install dependencies
              run: npm i ts-strictify

            - name: log git version
              run: git --version

            - name: Check coding rules
              run: ts-strictify --targetBranch="origin/main"
